import Badge from './Badge';
import { formatDate } from '../utils/formatDate';

/**
 * AISummaryBlock — displays the AI-powered case analysis.
 *
 * Props:
 *   aiSummary  { recommendedCourt, parsedSummary, generatedAt } | null
 *
 * Returns null if aiSummary is not provided.
 */
const AISummaryBlock = ({ aiSummary }) => {
  if (!aiSummary) return null;

  return (
    <div className='bg-navy/5 border border-sky rounded-lg p-5'>
      {/* Header row */}
      <div className='flex items-center gap-2 mb-3'>
        <span className='text-caption font-semibold text-steel uppercase tracking-wider'>
          Case Analysis
        </span>
        <span className='text-caption text-slate'>·</span>
        <span className='text-caption text-slate'>
          Generated {formatDate(aiSummary.generatedAt)}
        </span>
      </div>

      {/* Recommended court */}
      <div className='flex items-center gap-2 mb-4'>
        <span className='text-body font-semibold text-navy'>Recommended Court:</span>
        <Badge status={aiSummary.recommendedCourt} />
      </div>

      {/* Relevance score */}
      {aiSummary.relevanceScore != null && (
        <div className='flex items-center gap-2 mb-4'>
          <span className='text-body font-semibold text-navy'>Relevance:</span>
          <div className='flex items-center gap-1.5'>
            {[1, 2, 3, 4, 5].map((dot) => (
              <div
                key={dot}
                className={`w-2.5 h-2.5 rounded-full ${
                  dot <= Math.round(aiSummary.relevanceScore * 5) ? 'bg-steel' : 'bg-sky/50'
                }`}
              />
            ))}
            <span className='text-caption text-slate ml-1'>
              {Math.round(aiSummary.relevanceScore * 5)}/5
            </span>
          </div>
        </div>
      )}

      {/* Summary text */}
      <p className='text-body text-slate leading-relaxed'>{aiSummary.parsedSummary}</p>

      {/* Disclaimer */}
      <p className='text-caption text-slate/70 mt-4 border-t border-sky pt-3'>
        This analysis was generated by an AI assistant and reviewed for sensitive content
        before display. The court recommendation is advisory only.
      </p>
    </div>
  );
};

export default AISummaryBlock;
