import Badge from './Badge';
import { formatDateTime } from '../utils/formatDate';

export default function AISummaryBlock({ aiSummary }) {
  if (!aiSummary) return null;

  return (
    <div className="bg-navy/5 border border-sky rounded-lg p-5">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-caption font-semibold text-steel uppercase tracking-wider">
          AI Assessment
        </span>
        <span className="text-caption text-slate">·</span>
        <span className="text-caption text-slate">
          Generated {formatDateTime(aiSummary.generatedAt)}
        </span>
      </div>

      <div className="flex items-center gap-2 mb-4">
        <span className="text-body font-semibold text-navy">Recommended Court:</span>
        <Badge status={aiSummary.recommendedCourt} />
      </div>

      {aiSummary.relevanceScore && (
        <div className="flex items-center gap-2 mb-4">
          <span className="text-body font-semibold text-navy">Relevance Score:</span>
          <div className="flex gap-1">
            {[1, 2, 3, 4, 5].map((dot) => (
              <div
                key={dot}
                className={`w-3 h-3 rounded-full ${
                  dot <= aiSummary.relevanceScore ? 'bg-steel' : 'bg-sky/50'
                }`}
              />
            ))}
          </div>
          <span className="text-caption text-slate">{aiSummary.relevanceScore}/5</span>
        </div>
      )}

      <p className="text-body text-slate leading-relaxed">{aiSummary.parsedSummary}</p>

      <p className="text-caption text-slate/70 mt-4 border-t border-sky pt-3">
        This summary was generated by an AI assistant and reviewed for sensitive content before
        display. The court recommendation is advisory only.
      </p>
    </div>
  );
}
